# Generated by Django 5.1 on 2025-01-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
